# -------------------------------------------------------
# --- Examples for tweaking a Fabric Studio instance. ---
# -------------------------------------------------------

# uncomment what you want to execute
# add a sleep timer by adding ";sleep x" after a command line

#-Adding SSK-keys-#
#system account ssh keys add "<your-public-key-here>" ;sleep 5

#-Extending WebUI timeout 8h-#
#system security preferences set '{\"web_session_age\": 28800}'

#-Extending WebUI timeout 8h-#
#system security preferences set '{\"web_session_age\": 28800}'

#-Setting Fabric Studio Hostname-#
#system hostname set Attendee - #${COUNT}

#-Changing guest password to YOURPASSWORD-#
#system user password change --new-password YOURPASSWORD guest

#-Killing all tasks-#
#task kill-all ; sleep 10

#-Uninstalling fabric-#
#runtime fabric uninstall

#-Synchronise all repositories-#
#system repository remote refresh-all

#-Removing all workspaces-#
#model fabric batch delete --no-interactive

#-Purging files-#
#execute purge files --yes

#-Purging logs-#
#execute purge logs --yes

#-Downloading template FortiWeb AI and CSP v0.1.8-#
#system repository template sync-download templates/appsec-team/FortiWeb-AI-and-CSP-workshop-0.1.9.zip

#-Creating workspace FortiWeb AI and CSP-#
#model fabric create "FortiWeb AI and CSP"

#-Install workspace-#
#runtime fabric install 1

#-Download workspace documentation-#
#runtime fabric documentation download

#-Prefetching all POC-definitions-#
#poc prefetch all" # This is pending NFR