# ----------------------------------------------------------------------
# --- Put your Fabric Studio CLI commands to execute below this line ---
# ----------------------------------------------------------------------

#echo "[*] Adding SSK-keys"; sshfpoc 'system account ssh keys add "<your-public-key-here>"'

#echo "[*] Extending WebUI timeout 8h"; sshfpoc "system security preferences set '{\"web_session_age\": 28800}'"

#
# Example for tweaking a Fabric Studio instance.
#
#echo "[*] Extending WebUI timeout 8h"; sshfpoc "system security preferences set '{\"web_session_age\": 28800}'"
#echo "[*] Setting Fabric Studio Hostname"; sshfpoc "system hostname set Attendee - #${COUNT}"
#echo "[*] Changing guest password to YOURPASSWORD"; sshfpoc 'system user password change --new-password PASSWORD guest'
#echo "[*] Killing all tasks"; sshfpoc 'task kill-all'
#echo "[*] Uninstalling fabric"; sshfpoc 'runtime fabric uninstall'
#echo "[*] Synchronise all repositories"; sshfpoc 'system repository remote refresh-all'
#echo "[*] Removing all workspaces"; sshfpoc 'model fabric batch delete --no-interactive'
##echo "[*] Purging files "; sshfpoc 'execute purge files --yes'
##echo "[*] Purging logs "; sshfpoc 'execute purge logs --yes'
#echo "[*] Downloading template FortiWeb AI and CSP v0.1.8"; sshfpoc 'system repository template sync-download templates/appsec-team/FortiWeb-AI-and-CSP-workshop-0.1.9.zip'
#echo "[*] Creating workspace FortiWeb AI and CSP"; sshfpoc 'model fabric create "FortiWeb AI and CSP"'
#echo "[*] Install workspace"; sshfpoc "runtime fabric install 1"
#echo "[*] Download workspace documentation"; sshfpoc "runtime fabric documentation download"
##echo "[*] Prefetching all POC-definitions"; sshfpocparallel "poc prefetch all" # This is pending NFR
